language: java
jdk:
  - oraclejdk8
env:
  - TEST_DIR=cucumber-example
  - TEST_DIR=may-the-feature-be-with-you
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm
    && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm
    install "6"
  - npm install
addons:
  sonarqube:
    token:
        secure: rFLC0TWp5MqrCaPnc02mzr4CTwy6osgcspanQ7p+log+XJTkAWcCVPbBvFHwJXfBuPG52qDFfDDL2SGE8UACuZqnK2st+btv6U5qRQ2TSfra0JsCJOp2btJLpxVZO7vaOT0mPS9nOKJM+xJ0D/8kDnxNXkhCQxZAIWUKaNUetTrJ8W5Xg85E85AxEH7hQs6gBwsaqMIFcCzdcyzEX8VdH8d1n0fNsSqHBgDxLQDk9O6btWqH8T+obXNKkL/jr+HjuPQwiNf8FSRwz1TigjJT1itpKBiACmYL402lay/aPNplnUibDQg9X9aX2vVwSqhywTuVX9erDBmILyUaPRFkpsv7OIwgo6ruLMsl05/VRwcOp7GrAfAnVb5vCGUTHqXeVL0CHzbFJHmYwi9WsPRDuJpxudIkAdOsFOaOJUJ1mQV6zucgZHH9KhdtSpqErx0xIejS6BSm4vCkmclVWMCkeEYrGqsJV5hbWCJlnzIx+Fa1b7H61+AmDZtqHpw0DqjQdKrIw3wM7fCTb4J2kGqG2EQvGrHw/C8hw2MWX4Ql/2fULOcpSdLTcqn1Cx7iW0bTukxpW0BmDVJHU/J6ysHwsXEhGV5B3FUvDa/T6vo9KrIdNz276CLVXt6JQoWyCQ4KNx6SYhY8JqesW6XEMvjmo7JdOsG/xbzyL7nnR21LZWk=
    branches:
        - master
        - jug_toulouse
        - agile_france
        - young_blood
script:
  - cd $TEST_DIR && mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
